const householdTasks = [
  "Making the bed",
  "Washing dishes",
  "Wiping down kitchen counters",
  "Sweeping kitchen floor",
  "Preparing meals",
  "Feeding pets",
  "Taking out trash",
  "Sorting mail",
  "Watering indoor plants",
  "Picking up clutter",
  "Doing a load of laundry",
  "Wiping bathroom surfaces",
  "Sanitizing doorknobs and light switches",
  "Checking food supplies",
  "Planning the next day’s meals",
  "Vacuuming all rugs and carpets",
  "Mopping floors",
  "Cleaning the bathrooms",
  "Dusting furniture",
  "Changing bedding",
  "Laundry (clothes, towels, linens)",
  "Ironing clothes",
  "Grocery shopping",
  "Meal prepping",
  "Cleaning mirrors",
  "Dusting and cleaning home decor",
  "Organizing pantry",
  "Cleaning out the fridge",
  "Bathing pets",
  "Yard work (mowing lawn, trimming bushes)",
  "Deep cleaning the kitchen",
  "Cleaning the oven",
  "Washing windows",
  "Dusting blinds or shutters1",
  "Organizing closets1",
  "Checking smoke detectors",
  "Cleaning light fixtures",
  "Washing car",
  "Cleaning garage",
  "Sharpening kitchen knives",
  "Cleaning under furniture",
  "Washing throw pillows and blankets",
  "Cleaning out the freezer",
  "Weeding the garden1",
  "Cleaning gutters",
  "Deep cleaning carpets",
  "Sealing grout lines",
  "Cleaning fireplace",
  "Storing seasonal clothing",
  "Preparing garden for new season",
  "Fertilizing lawn",
  "Cleaning patio furniture",
  "Draining and storing hoses",
  "Checking insulation",
  "Winterizing home",
  "Cleaning BBQ grill",
  "Organizing storage areas",
  "Decluttering spaces",
  "Donating unused items",
  "Planning home improvement projects",
  "Repainting walls",
  "Restocking essential supplies",
  "Updating home inventory",
  "Servicing major appliances",
  "Checking plumbing for leaks",
  "Replacing worn-out tools",
  "Planning for holidays",
  "Hosting guests",
  "Rearranging furniture",
  "Updating security systems",
  "Reviewing insurance policies",
  "Budgeting for expenses",
  "Cleaning drapes and curtains",
  "Maintaining vehicles",
  "Reviewing family emergency plans",
  "Paying bills",
  "Filing important documents",
  "Scheduling appointments",
  "Reviewing bank statements",
  "Planning family schedules",
  "Corresponding with friends and family",
  "Updating contact lists",
  "Managing subscriptions",
  "Organizing digital files",
  "Backing up important data",
  "Scheduling medical check-ups",
  "Refilling prescriptions",
  "Planning exercise routines",
  "Preparing healthy snacks",
  "Tracking health metrics",
  "Cleaning sports equipment",
  "Organizing medical records",
  "Researching health information",
  "Planning relaxation activities",
  "Creating a first-aid kit",
  "Helping with homework",
  "Planning educational outings",
  "Organizing school supplies",
  "Setting up study areas",
  "Reviewing school communications",
];

const schoolTasks = [
  "Attending classes",
  "Taking notes during lectures",
  "Completing homework assignments",
  "Participating in class discussions",
  "Reading textbooks and other materials",
  "Studying for quizzes and exams",
  "Working on group projects",
  "Presenting reports and presentations",
  "Conducting research for papers",
  "Taking part in extracurricular activities",
  "Volunteering for school events",
  "Organizing personal study schedules",
  "Meeting with academic advisors",
  "Applying for scholarships",
  "Preparing for standardized tests",
  "Planning lessons",
  "Grading assignments and exams",
  "Providing feedback to students",
  "Attending faculty meetings",
  "Continuing professional development",
  "Communicating with parents",
  "Managing classroom behavior",
  "Creating educational materials",
  "Supervising lunch and recess",
  "Coordinating with other teachers",
  "Advising student clubs",
  "Organizing field trips",
  "Updating student records",
  "Implementing school policies",
  "Participating in teacher training workshops",
  "Enrolling new students",
  "Maintaining student records",
  "Managing school finances",
  "Coordinating transportation services",
  "Overseeing facility maintenance",
  "Planning school-wide events",
  "Implementing safety protocols",
  "Handling parent inquiries",
  "Scheduling school calendar",
  "Supporting technology infrastructure",
  "Facilitating staff hiring",
  "Conducting performance evaluations",
  "Ensuring compliance with regulations",
  "Managing school supplies inventory",
  "Coordinating with external organizations",
  "Preparing classrooms for the day",
  "Assisting in the library",
  "Providing technical support",
  "Serving meals in the cafeteria",
  "Cleaning school facilities",
  "Operating the school office",
  "Managing lost and found items",
  "Assisting with student health needs",
  "Supervising student transitions",
  "Providing security on campus",
  "Coaching sports teams",
  "Offering tutoring services",
  "Facilitating after-school programs",
  "Organizing storage areas",
  "Handling emergency situations",
  "Setting educational goals",
  "Developing school policies",
  "Reviewing curriculum standards",
  "Allocating resources",
  "Engaging with the community",
  "Evaluating superintendent performance",
  "Approving budgets",
  "Advocating for legislative changes",
  "Monitoring student achievement",
  "Addressing stakeholder concerns",
  "Guiding students in course selection",
  "Providing career counseling",
  "Supporting student mental health",
  "Facilitating conflict resolution",
  "Coordinating college application process",
  "Leading student workshops",
  "Managing intervention programs",
  "Assessing student progress",
  "Collaborating with teachers and parents",
  "Organizing peer mentoring",
  "Planning club meetings",
  "Organizing team practices",
  "Coordinating performances",
  "Fundraising for events",
  "Managing club budgets",
  "Recruiting new members",
  "Training student leaders",
  "Scheduling competitions",
  "Publicizing events",
  "Evaluating program effectiveness",
  "Repairing school equipment",
  "Landscaping school grounds",
  "Inspecting safety equipment",
  "Painting and decorating",
  "Managing waste disposal",
  "Conducting routine inspections",
  "Addressing plumbing issues",
  "Ensuring energy efficiency",
  "Preparing facilities for special events",
  "Responding to maintenance requests",
];

const homeProjectTasks = [
  "Painting a room",
  "Installing new light fixtures",
  "Replacing door handles",
  "Updating cabinet hardware",
  "Organizing the garage",
  "Creating a picture wall",
  "Planting a flower bed",
  "Installing a new faucet",
  "Hanging new curtains",
  "Assembling new furniture",
  "Building a bookshelf",
  "Crafting a headboard for your bed",
  "Making a homemade candle",
  "Sewing your own throw pillows",
  "Creating a mosaic tile backsplash",
  "Refinishing an old piece of furniture",
  "Building a birdhouse",
  "Making a garden path",
  "Crafting a wooden planter box",
  "DIYing a fire pit",
  "Cleaning gutters",
  "Power washing the siding",
  "Sealing a deck",
  "Fixing a leaky faucet",
  "Repairing drywall",
  "Replacing air filters",
  "Draining the water heater",
  "Insulating the attic",
  "Caulking windows and doors",
  "Servicing the HVAC system",
  "Installing closet organizers",
  "Setting up a home office",
  "Building garage shelving",
  "Creating a pantry inventory system",
  "Organizing a mudroom",
  "Sorting through old clothes",
  "Setting up a recycling system",
  "Organizing digital files",
  "Creating a command center",
  "Labeling storage containers",
  "Building a patio",
  "Installing a sprinkler system",
  "Landscaping the front yard",
  "Building a fence",
  "Creating an outdoor kitchen",
  "Installing outdoor lighting",
  "Building a greenhouse",
  "Setting up a compost bin",
  "Creating a rain garden",
  "Installing a new mailbox",
  "Installing solar panels",
  "Upgrading to energy-efficient appliances",
  "Adding weather stripping",
  "Installing a programmable thermostat",
  "Upgrading insulation",
  "Installing LED lighting",
  "Setting up a smart home system",
  "Installing energy-efficient windows",
  "Adding a storm door",
  "Conducting an energy audit",
  "Installing smoke detectors",
  "Setting up a security system",
  "Adding motion sensor lights",
  "Installing carbon monoxide detectors",
  "Creating a family emergency plan",
  "Assembling a disaster supply kit",
  "Installing a radon mitigation system",
  "Childproofing the home",
  "Securing heavy furniture to walls",
  "Testing for lead paint",
  "Replacing a toilet",
  "Installing a new showerhead",
  "Updating bathroom tiles",
  "Installing a bathroom vanity",
  "Adding a bathroom exhaust fan",
  "Regrouting shower tiles",
  "Installing a new bathroom mirror",
  "Adding storage solutions",
  "Upgrading to a low-flow toilet",
  "Installing a towel warmer",
  "Refacing kitchen cabinets",
  "Installing a new kitchen sink",
  "Adding a tile backsplash",
  "Upgrading kitchen countertops",
  "Installing a new dishwasher",
  "Adding under-cabinet lighting",
  "Building a kitchen island",
  "Installing a new range hood",
  "Organizing kitchen drawers",
  "Upgrading to a smart refrigerator",
  "Installing hardwood floors",
  "Laying down tile flooring",
  "Putting in laminate flooring",
  "Refinishing hardwood floors",
  "Installing carpet in bedrooms",
  "Adding area rugs",
  "Installing heated floors",
  "Replacing stair treads",
  "Installing baseboards",
  "Laying down vinyl flooring",
];

export { householdTasks, schoolTasks, homeProjectTasks };
